### ISSUE TITLE
docs or command example

### ISSUE THREAD

**Issue by progressify** [moses-palmer/maze.py#1]
hi dear
where i can find an online documentation or a full example of the cli command for generating (and save )the maze? (with and without the solution)

thankyou!

I am on macOS and I tried:

```
 amaze --walls 6 --image-output maze1.png --maze-size 100 100 --image-room-size 200 200
```

I receive this error:

```
This maze cannot be printed as it is not square
Traceback (most recent call last):
  File "/myvenv/bin/amaze", line 5, in <module>
    main()
  File "/myvenv/lib/python3.8/site-packages/amaze/__init__.py", line 245, in main
    make_image(maze, solution, **dict(
  File "/myvenv/lib/python3.8/site-packages/amaze/image.py", line 203, in make_image
    min_x, min_y, max_x, max_y = calculate_bounds(maze)
  File "/myvenv/lib/python3.8/site-packages/amaze/image.py", line 44, in calculate_bounds
    min_x, min_y = min(min_x, px), min(min_y, py)
TypeError: '<' not supported between instances of 'float' and 'infinity'
```

**Comment by moses-palmer** [comment]
Thank you for your report.

I think this may be caused by incompatibilities between the version of Python I used seven years ago to develop this application and more recent version. As you see from the commit history, this repository is stale.

I have however developed a new version of this library/application [here](https://github.com/moses-palmer/labyru); it is however developed in Rust, which may complicate matters for you. This version does however build with recent versions of Rust, and the performance is greatly improved. This repository, I am sorry to say, will not receive any updates from me.
